use gym_db;

INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "1", "pm", "24 Hour Fitness", NULL, "1");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "2", "pm", "24 Hour Fitness", NULL, "2");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "3", "pm", "24 Hour Fitness", NULL, "3");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "4", "pm", "24 Hour Fitness", NULL, "4");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "5", "pm", "24 Hour Fitness", NULL, "5");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "6", "pm", "24 Hour Fitness", NULL, "6");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "7", "pm", "24 Hour Fitness", NULL, "7");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "8", "pm", "24 Hour Fitness", NULL, "8");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "9", "pm", "24 Hour Fitness", NULL, "9");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "10", "pm", "24 Hour Fitness", NULL, "10");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "11", "pm", "24 Hour Fitness", NULL, "11");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "12", "pm", "24 Hour Fitness", NULL, "12");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "1", "pm", "24 Hour Fitness", NULL, "1");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "2", "pm", "24 Hour Fitness", NULL, "2");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "3", "pm", "24 Hour Fitness", NULL, "3");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "4", "pm", "24 Hour Fitness", NULL, "4");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "5", "pm", "24 Hour Fitness", NULL, "5");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "6", "pm", "24 Hour Fitness", NULL, "6");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "7", "pm", "24 Hour Fitness", NULL, "7");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "8", "pm", "24 Hour Fitness", NULL, "8");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "9", "pm", "24 Hour Fitness", NULL, "9");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "10", "pm", "24 Hour Fitness", NULL, "10");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "11", "pm", "24 Hour Fitness", NULL, "11");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "12", "pm", "24 Hour Fitness", NULL, "12");
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "1", "pm", "24 Hour Fitness", "1" , NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "2", "pm", "24 Hour Fitness", "2", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "3", "pm", "24 Hour Fitness", "3", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "4", "pm", "24 Hour Fitness", "4", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "5", "pm", "24 Hour Fitness", "5", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "6", "pm", "24 Hour Fitness", "6", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "7", "pm", "24 Hour Fitness", "7", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "8", "pm", "24 Hour Fitness", "8", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "9", "pm", "24 Hour Fitness", "9", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "10", "pm", "24 Hour Fitness", "10", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "11", "pm", "24 Hour Fitness", "11", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "12", "pm", "24 Hour Fitness", "12", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "1", "pm", "24 Hour Fitness", "1", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "2", "pm", "24 Hour Fitness", "2", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "3", "pm", "24 Hour Fitness", "3", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "4", "pm", "24 Hour Fitness", "4", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "5", "pm", "24 Hour Fitness", "5", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "6", "pm", "24 Hour Fitness", "6", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "7", "pm", "24 Hour Fitness", "7", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "8", "pm", "24 Hour Fitness", "8", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "9", "pm", "24 Hour Fitness", "9", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "10", "pm", "24 Hour Fitness", "10", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "11", "pm", "24 Hour Fitness", "11", NULL);
INSERT INTO Appointments (month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("9", "18", "12", "pm", "24 Hour Fitness", "12", NULL);


SELECT * FROM gym_db.Appointments;