use gym_db;

INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("rdavis", "9", "18", "1", "pm", "24 Hour Fitness", NULL, "1");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("jgarcia", "9", "18", "2", "pm", "24 Hour Fitness", NULL, "2");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("psmith", "9", "18", "3", "pm", "24 Hour Fitness", NULL, "3");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("plee", "9", "18", "4", "pm", "24 Hour Fitness", NULL, "4");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("zdouglas", "9", "18", "5", "pm", "24 Hour Fitness", NULL, "5");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("rnicholas", "9", "18", "6", "pm", "24 Hour Fitness", NULL, "6");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("sbrown", "9", "18", "7", "pm", "24 Hour Fitness", NULL, "7");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("sgonzales", "9", "18", "8", "pm", "24 Hour Fitness", NULL, "8");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("kjohnson", "9", "18", "9", "pm", "24 Hour Fitness", NULL, "9");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("mraymond", "9", "18", "10", "pm", "24 Hour Fitness", NULL, "10");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("aphilips", "9", "18", "11", "pm", "24 Hour Fitness", NULL, "11");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("sericson", "9", "18", "12", "pm", "24 Hour Fitness", NULL, "12");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("jdavis", "9", "18", "1", "pm", "24 Hour Fitness", NULL, "13");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("egarcia", "9", "18", "2", "pm", "24 Hour Fitness", NULL, "14");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("hsmith", "9", "18", "3", "pm", "24 Hour Fitness", NULL, "15");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("slee", "9", "18", "4", "pm", "24 Hour Fitness", NULL, "16");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("bdouglas", "9", "18", "5", "pm", "24 Hour Fitness", NULL, "17");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("snicholas", "9", "18", "6", "pm", "24 Hour Fitness", NULL, "18");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("rbrown", "9", "18", "7", "pm", "24 Hour Fitness", NULL, "19");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("mgonzales", "9", "18", "8", "pm", "24 Hour Fitness", NULL, "20");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("djohnson", "9", "18", "9", "pm", "24 Hour Fitness", NULL, "21");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("traymond", "9", "18", "10", "pm", "24 Hour Fitness", NULL, "22");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("jphilips", "9", "18", "11", "pm", "24 Hour Fitness", NULL, "23");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("sellis", "9", "18", "12", "pm", "24 Hour Fitness", NULL, "24");
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("hdavis", "9", "18", "1", "pm", "24 Hour Fitness", "1" , NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("egarcia", "9", "18", "2", "pm", "24 Hour Fitness", "2", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("lsmith", "9", "18", "3", "pm", "24 Hour Fitness", "3", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("rlee", "9", "18", "4", "pm", "24 Hour Fitness", "4", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("bdouglas", "9", "18", "5", "pm", "24 Hour Fitness", "5", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("anicholas", "9", "18", "6", "pm", "24 Hour Fitness", "6", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("rbrown", "9", "18", "7", "pm", "24 Hour Fitness", "7", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("ygonzales", "9", "18", "8", "pm", "24 Hour Fitness", "8", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("ljohnson", "9", "18", "9", "pm", "24 Hour Fitness", "9", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("mraymond", "9", "18", "10", "pm", "24 Hour Fitness", "10", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("pphilips", "9", "18", "11", "pm", "24 Hour Fitness", "11", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("aericson", "9", "18", "12", "pm", "24 Hour Fitness", "12", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("ddavis", "9", "18", "1", "pm", "24 Hour Fitness", "13", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("agarcia", "9", "18", "2", "pm", "24 Hour Fitness", "14", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("rsmith", "9", "18", "3", "pm", "24 Hour Fitness", "15", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("hlee", "9", "18", "4", "pm", "24 Hour Fitness", "16", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("jdouglas", "9", "18", "5", "pm", "24 Hour Fitness", "17", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("nnicholas", "9", "18", "6", "pm", "24 Hour Fitness", "18", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("bbrown", "9", "18", "7", "pm", "24 Hour Fitness", "19", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("tgonzales", "9", "18", "8", "pm", "24 Hour Fitness", "20", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("bjohnson", "9", "18", "9", "pm", "24 Hour Fitness", "21", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("jraymond", "9", "18", "10", "pm", "24 Hour Fitness", "22", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("ephilips", "9", "18", "11", "pm", "24 Hour Fitness", "23", NULL);
INSERT INTO Appointments (userName, month, day, time, am_pm, gym, RookieId, ExpertId) VALUES ("pericson", "9", "18", "12", "pm", "24 Hour Fitness", "24", NULL);

SELECT * FROM gym_db.Appointments;