INSERT INTO Members (firstName, lastName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Henry", "Davis", "User", "24 Hour Fitness", 92629, "September", "15","3", "PM");
INSERT INTO Members (firstName, lastName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Jessica", "Garcia", "Trainer", "LA Fitness", 92663, "September", "15","3", "PM");
INSERT INTO Members (firstName, lastName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Louis", "Smith", "User", "24 Hour Fitness", 90007, "September", "15","3", "PM");
INSERT INTO Members (firstName, lastName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Rhonda", "Lee", "User", "LA Fitness", 92646, "September", "16","6", "PM");
INSERT INTO Members (firstName, lastName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Zeke", "Douglas", "Trainer", "24 Hour Fitness", 92629, "September", "15","5", "PM");
INSERT INTO Members (firstName, lastName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Ronald", "Nicholas", "Trainer", "LA Fitness", 92663, "September", "16","2", "PM");
INSERT INTO Members (firstName, lastName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Memphis", "Brown", "User", "24 Hour Fitness", 90007, "September", "15","10", "AM");
INSERT INTO Members (firstName, lastName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Stephanie", "Gonzales", "Trainer", "LA Fitness", 92646, "September", "13","5", "PM");
INSERT INTO Members (firstName, lastName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Larry", "Johnson", "User", "24 Hour Fitness", 92629, "September", "17","11", "AM");
INSERT INTO Members (firstName, lastName, type, gym, zipCode, month, day, time, am_pm) VALUES ("May", "Raymond", "Trainer", "LA Fitness", 92663, "September", "14","4", "PM");
INSERT INTO Members (firstName, lastName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Peter", "Philips", "User", "24 Hour Fitness", 90007, "September", "17","3", "PM");
INSERT INTO Members (firstName, lastName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Amy", "Ericson", "User", "LA Fitness", 92646, "September", "16","7", "PM");
