INSERT INTO Members (firstName, lastName, userName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Henry", "Davis", "hdavis", "User", "24 Hour Fitness", 92629, "September", "15","3", "PM");
INSERT INTO Members (firstName, lastName, userName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Jessica", "Garcia", "jgarcia", "Trainer", "LA Fitness", 92663, "September", "15","3", "PM");
INSERT INTO Members (firstName, lastName, userName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Louis", "Smith", "lsmith", "User", "24 Hour Fitness", 90007, "September", "15","3", "PM");
INSERT INTO Members (firstName, lastName, userName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Rhonda", "Lee", "rlee", "User", "LA Fitness", 92646, "September", "16","6", "PM");
INSERT INTO Members (firstName, lastName, userName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Zeke", "Douglas", "zdouglas", "Trainer", "24 Hour Fitness", 92629, "September", "15","5", "PM");
INSERT INTO Members (firstName, lastName, userName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Ronald", "Nicholas", "rnicholas", "Trainer", "LA Fitness", 92663, "September", "16","2", "PM");
INSERT INTO Members (firstName, lastName, userName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Memphis", "Brown", "mbrown", "User", "24 Hour Fitness", 90007, "September", "15","10", "AM");
INSERT INTO Members (firstName, lastName, userName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Stephanie", "Gonzales", "sgonzales", "Trainer", "LA Fitness", 92646, "September", "13","5", "PM");
INSERT INTO Members (firstName, lastName, userName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Larry", "Johnson", "ljohnson", "User", "24 Hour Fitness", 92629, "September", "17","11", "AM");
INSERT INTO Members (firstName, lastName, userName, type, gym, zipCode, month, day, time, am_pm) VALUES ("May", "Raymond", "mraymond", "Trainer", "LA Fitness", 92663, "September", "14","4", "PM");
INSERT INTO Members (firstName, lastName, userName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Peter", "Philips", "pphilips", "User", "24 Hour Fitness", 90007, "September", "17","3", "PM");
INSERT INTO Members (firstName, lastName, userName, type, gym, zipCode, month, day, time, am_pm) VALUES ("Amy", "Ericson", "aericson", "User", "LA Fitness", 92646, "September", "16","7", "PM");
